version: '3.8'

services:
  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    ports:
      - "2003:2003"   # Plaintext metrics input port
      - "2004:2004"   # Pickle protocol port
      - "8182:80"     # Graphite Web UI port
    environment:
      - REDIS_TAGDB=1       # Enable Redis for TagDB
      - COLLECTD=1          # Enable Collectd service
      - RELAY=1             # Enable carbon-relay
      - GOCARBON=1          # Enable go-carbon
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5s
      timeout: 3s
      retries: 10

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "8181:3000"   # Grafana UI
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - graphite
    restart: always

  bookstore:
    build:
      context: .
    image: bookstore-app:latest  # 👈 This allows tagging/rollback
    container_name: bookstore
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - GRAPHITE_HOST=graphite
      - GRAPHITE_PORT=2003
    restart: always
    depends_on:
      - graphite
