version: '3.8'

services:
  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    ports:
      - "2003:2003"   # Plaintext metrics
      - "2004:2004"   # Pickle protocol
      - "8182:80"     # Graphite Web UI (container exposes it on port 80)
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "8181:3000"   # Grafana UI is on 3000 inside container
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - graphite
    restart: always

  bookstore:
    build: .
    container_name: bookstore
    ports:
      - "8081:8081"   # Spring Boot app
    environment:
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      - graphite
    restart: always
