version: '3.8'

services:
  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    ports:
      - "2003:2003"  
      - "2004:2004"   
      - "8182:80"     
    environment:
      - REDIS_TAGDB=1       
      - COLLECTD=1          
      - RELAY=1            
      - GOCARBON=1          
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5s
      timeout: 3s
      retries: 10

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "8181:3000"   
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - graphite
    restart: always

  bookstore:
    build:
      context: .
    image: bookstore-app:latest 
    container_name: bookstore
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - GRAPHITE_HOST=graphite
      - GRAPHITE_PORT=2003
    restart: always
    depends_on:
      - graphite
