# rollback.yml
- name: Rollback to previous working Docker image
  hosts: local
  become: yes
  tasks:

    - name: Stop current containers
      shell: docker compose down
      args:
        chdir: "{{ playbook_dir }}/.."  # go to root dir

    - name: Retag backup as latest
      shell: docker image tag bookstore-app:backup bookstore-app:latest
      ignore_errors: no

    - name: Restart containers with backup image
      shell: docker compose up -d
      args:
        chdir: "{{ playbook_dir }}/.."
